language: groovy

env:
 - GROOVY_VERSION=2.4.15
 - GROOVY_VERSION=2.5.2

jdk:
  - oraclejdk8
  - oraclejdk9

script: ./gradlew -i -Pgroovy_version=${GROOVY_VERSION}

after_success:
  - ./gradlew coveralls
