site_name: jenkins-shared-library
site_author: 'Thomas Lehmann <thomas.lehmann.private@gmail.com'
site_url: 'https://nachtfeuer.github.io/jenkins-shared-library/'
repo_url: 'https://github.com/Nachtfeuer/jenkins-shared-library'

nav:
    - Home: index.md
    - User Guide:
      - documentation.md
      - gradle.md
    - DSL:
      - virtualenv.md
      - xgradle.md
      - jobdslcode.md
      - xgit.md
      - xpublish.md

theme: readthedocs
